# Dependencies
markdown:         redcarpet
highlighter: rouge

# Permalinks
permalink:       /posts/:year/:month/:day/:title

# Setup
title:            My Own Ruby
tagline:          Learning Ruby
url:              http://menikdp.github.io
paginate:         5
baseurl:          /
author:
  name:           Menik Damayanti P
  url:            https://twitter.com/_menikdp
  email:          menik.damayanti.p@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# Handling Reading
exclude:      ["Gemfile", "Gemfile.lock", "Rakefile", "lib/tasks/*"]