# Dependencies
markdown:         redcarpet
pygments:         false

# Permalinks
permalink:       /posts/:year/:month/:day/:title

# Setup
title:            My Own Ruby
tagline:          Learning Ruby
url:              http://menikdp.github.io
paginate:         2
baseurl:          ""
author:
  name:           Menik Damayanti Pratiwi
  url:            https://twitter.com/_menikdp
  email:          menik.damayanti.p@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
